config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Django Template",
        default_version="v1",
        description="Django Template API Documentatio",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="victor.musembi11@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("docs/", include("docs.app.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docs/app/urls.py
"""Core URL Configuration."""
from django.urls import path

from .views import HomePageView

app_name = "core"

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

accounts/models.py
"""Accounts app models."""
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model with email as the unique identifier."""

    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        """Return str repr of the user."""
        return self.email

accounts/views.py
"""Account views."""

docs/app/views.py
"""Views for the core app."""
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    """Home page view."""

    template_name = "home.html"

docs/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap 5 CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>    

    {% include "partials/_navbar.html" %}

    <div class="container">
    {% block content %}{% endblock content %}
    </div>
    
    <!-- Bootstrap 5 JS CDN Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

docs/app/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}
<h1 class="mb-5 mt-5">
    Django Template
</h1>

<h2>Virtual environment setup</h2>
<hr>

<h4>Create virtual environment</h4>
<pre>
<code>python3 -m venv venv</code>
</pre>

<h4>Activate virtual environment</h4>
<pre>
<code>source venv/bin/activate</code>
</pre>

<h2>Environment variables setup</h2>
<hr>

<p>Create a <code>.env</code> file in the <strong>root directory</strong> and add the following variables in the .env.example file.</p>

<h4>Note:</h4>
<p>The default database is <strong>sqlite3</strong> on the local environment. If you want to use postgresql(or any other), then make sure you set the environment variables in the .env for the database as shown in the .env.example file so that the <strong>DB_IS_AVAIL</strong> variable in <strong>config.settings.local</strong> is set to <strong>True</strong>.</p>

<h2>Install dependencies</h2>
<hr>

<pre>
<code>pip install -r requirements.txt</code>
</pre>

<h2>Run migrations</h2>
<hr>

<pre>
<code>python manage.py migrate</code>
</pre>

<h2>Run server</h2>
<hr>

<pre>
<code>python manage.py runserver</code>
</pre>

<h2>Docker setup</h2>
<hr>

<h4>Note:</h4>
<p>The default port for postgresql is <strong>5432</strong> but in the Docker setup, the port is <strong>5435</strong>. So, make sure you change the port number in the .env file when using Docker.</p>

<h4>Build image and run container</h4>
<pre>
    <code>docker-compose up --build</code>
</pre>

<h4>List images</h4>
<pre>
    <code>docker images</code>
</pre>

<h4>List containers</h4>
<pre>
    <code>docker ps</code>
</pre>

{% endblock content %}

docs/app/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark"  style="background-color: #2e4d37;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'core:home' %}">Django template</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:home' %}">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>